# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('last_check', models.DateTimeField()),
                ('check_interval', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('content', models.TextField(blank=True, max_length=1048576, null=True)),
                ('date', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web_tools.RssFeed')),
            ],
        ),
        migrations.CreateModel(
            name='UrlContentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('replace_pattern', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_content', models.TextField(blank=True, default=b'', max_length=1048576)),
                ('last_check', models.DateTimeField()),
                ('check_interval', models.IntegerField(default=4)),
                ('change_size', models.IntegerField(default=0)),
            ],
        ),
    ]
