# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_web_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcontenttracker',
            name='last_content',
            field=models.TextField(blank=True, default=b'', max_length=2097152),
        ),
    ]
