# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tools', '0002_auto_20160406_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcontenttracker',
            name='replace_pattern',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
