# pylint: skip-file

# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2022-09-12 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tools', '0003_auto_20160408_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcontenttracker',
            name='ignore_http_errors',
            field=models.BooleanField(default=False),
        ),
    ]
