# pylint: skip-file
# Generated by Django 4.2.16 on 2024-11-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tools', '0004_urlcontenttracker_ignore_http_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlcontenttracker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlcontenttracker',
            name='last_content',
            field=models.TextField(blank=True, default='', max_length=2097152),
        ),
    ]
