# pylint: skip-file
# Generated by Django 5.2.16 on 2026-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_web_tools', '0005_alter_rssfeed_id_alter_rssitem_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssfeed',
            options={'verbose_name': 'RSS feed', 'verbose_name_plural': 'RSS feeds'},
        ),
        migrations.AlterModelOptions(
            name='rssitem',
            options={'verbose_name': 'RSS feed item', 'verbose_name_plural': 'RSS feed items'},
        ),
        migrations.AlterModelOptions(
            name='urlcontenttracker',
            options={'verbose_name': 'URL content tracker', 'verbose_name_plural': 'URL content trackers'},
        ),
        migrations.AddField(
            model_name='urlcontenttracker',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=2097152),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlcontenttracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
